[package]
name = "rust_geometry"
description = "A geometry library for problems in ICPC programming contests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
